// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHltQAcaY-IL8rsExYHIzlyj2t7PD_SU8',
    appId: '1:634773751892:web:787de4a8b0ab673c0945c1',
    messagingSenderId: '634773751892',
    projectId: 'read-right-cpsc4150',
    authDomain: 'read-right-cpsc4150.firebaseapp.com',
    storageBucket: 'read-right-cpsc4150.firebasestorage.app',
    measurementId: 'G-LWRFS8YND3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArvgqesqqQWSM6dL5u_SIptglsmgloo7I',
    appId: '1:634773751892:android:c7940e1326fd124b0945c1',
    messagingSenderId: '634773751892',
    projectId: 'read-right-cpsc4150',
    storageBucket: 'read-right-cpsc4150.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxktdU7pEmmaLcK-SE_rc5FCSR-_mbm3s',
    appId: '1:634773751892:ios:1f26f8d6d75071760945c1',
    messagingSenderId: '634773751892',
    projectId: 'read-right-cpsc4150',
    storageBucket: 'read-right-cpsc4150.firebasestorage.app',
    iosBundleId: 'com.example.readright',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxktdU7pEmmaLcK-SE_rc5FCSR-_mbm3s',
    appId: '1:634773751892:ios:1f26f8d6d75071760945c1',
    messagingSenderId: '634773751892',
    projectId: 'read-right-cpsc4150',
    storageBucket: 'read-right-cpsc4150.firebasestorage.app',
    iosBundleId: 'com.example.readright',
  );
}
